CREATE TABLE Groups (
	Group_ID TINYINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Description VARCHAR(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;

CREATE TABLE Users (
	Login VARCHAR(32) NOT NULL PRIMARY KEY,
	Password VARCHAR(32) NOT NULL,
	Group_ID TINYINT NOT NULL,
	FOREIGN KEY (Group_ID) REFERENCES Groups (Group_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;

CREATE TABLE Flat (
	Flat_ID SMALLINT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Address VARCHAR(32) NOT NULL,
	Building SMALLINT NOT NULL,
	Apartment SMALLINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8, COLLATE utf8_general_ci;

CREATE TABLE Person (
	Person_ID VARCHAR(8) NOT NULL PRIMARY KEY,
	First_name VARCHAR(32) NOT NULL,
	Name VARCHAR(32) NOT NULL,
	Last_name VARCHAR(32),
	Login VARCHAR(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8, COLLATE utf8_general_ci;

CREATE TABLE Owner (
	Person_ID VARCHAR(8),
	Flat_ID SMALLINT(5),
        FOREIGN KEY (Person_ID) REFERENCES Person (Person_ID),
        FOREIGN KEY (Flat_ID) REFERENCES Flat (Flat_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8, COLLATE utf8_general_ci;

CREATE TABLE Dispatcher (
	Dispatcher_ID SMALLINT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(32) NOT NULL,
	Login VARCHAR(32),
	FOREIGN KEY (Login) REFERENCES Users (Login)
) ENGINE=InnoDB DEFAULT CHARSET=utf8, COLLATE utf8_general_ci;

CREATE TABLE Works (
	Works_ID SMALLINT(5) NOT NULL PRIMARY KEY,
	Name VARCHAR(64),
	Description VARCHAR(256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8, COLLATE utf8_general_ci;

CREATE TABLE Request (
	Request_ID INT NOT NULL PRIMARY KEY,
	Person_ID VARCHAR(8) NOT NULL,							
	Flat_ID SMALLINT(5) NOT NULL,
	Works_ID SMALLINT(5) NOT NULL,
	Requested_time DATE,
	Dispatcher_ID SMALLINT(5),
	FOREIGN KEY (Person_ID) REFERENCES Person (Person_ID),
        FOREIGN KEY (Flat_ID) REFERENCES Flat (Flat_ID),
        FOREIGN KEY (Works_ID) REFERENCES Works (Works_ID),
        FOREIGN KEY (Dispatcher_ID) REFERENCES Dispatcher (Dispatcher_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8, COLLATE utf8_general_ci;

CREATE TABLE Worker (
	Worker_ID SMALLINT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(32) NOT NULL,
	Specialization VARCHAR(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8, COLLATE utf8_general_ci;

CREATE TABLE Plan (
	Request_ID INT,							
	Worker_ID SMALLINT(5),
	FOREIGN KEY (Request_ID) REFERENCES Request (Request_ID),
        FOREIGN KEY (Worker_ID) REFERENCES Worker (Worker_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8, COLLATE utf8_general_ci;